### ISSUE TITLE
Improve font rendering

### ISSUE THREAD

**Issue by tommyent** [mrkevinlin/join-redesign#2]
Figured I would try and sneak this into your pull request to joaomgcd. This is a big issue on Mac especially with bolded 
`-webkit-font-smoothing: antialiased;`

I don't see a reason to not apply it to everything unless you do

**Comment by tommyent** [comment]
I looked into this a bit and it appears that Materialize has done

**Comment by mrkevinlin** [comment]
Done. I snuck it into the body tag of the global and settings stylesheets.

**Comment by tommyent** [comment]
Awesome! 👍
